### ISSUE TITLE
Exploration is a poor characterization of the XML transition

### ISSUE THREAD

**Issue by martinthomson** [paulehoffman/draft-rswg-rfc7990-updates#16]
From the introduction of -04:

> Based on the discussions with communities of interest, such as the IETF, the RFC Series Editor decided to explore a change to the format of the Series. 

This is a little misleading, without saying something like:

> RFC 7990 was the culmination of that exploration and loosely represents the current state of the RFC publication process.

**Comment by paulehoffman** [comment]
Sorry, forgot about this. I added "{{RFC7990}} was the culmination of that exploration." without the latter part that would be contentious.
