### ISSUE TITLE
Archival requirements

### ISSUE THREAD

**Issue by martinthomson** [paulehoffman/draft-rswg-rfc7990-updates#23]
First, a nitpick:

> The RPC will keep archived set of all definitive versions of RFCs as well as archived sets of the publication versions for an RFC that were published. 

There is only one definitive version.  I suggest the term "archived version" for a formerly-definitive version of an RFC.  This would then say:

> The RPC will maintain an archive of all versions of RFCs that were at any time definitive. An archived version is a document that was previously a definitive version.

Second, I don't think that we need to state the requirement this way.  I would prefer that we instead say:

> The RPC will provide the means to obtain publication versions for each archived version, either by storing files or by providing the means to generate those files from the archived version.

Fundamentally, the idea that the RPC has the discretion to replace publication versions is a good one, but it is incompatible with a hard requirement to archive publication versions.  While archival is a fine idea if it is on a best effort basis, as the other text suggests, requiring archival as the current text does makes it hard/impossible to definitively point at what content needs to be archived.

Third, should the archives record the period over which an archived version was definitive, not just when it was published, but also when it was replaced?

**Comment by paulehoffman** [comment]
If this is still an active concern, it should be on the list, not here in the repo.
