### ISSUE TITLE
Include the RSAB in the decision making

### ISSUE THREAD

**Issue by paulehoffman** [paulehoffman/draft-rswg-rfc7990-updates#4]
From Brian Carpenter: Add the RSAB to:
```The RFC Series Working Group (RSWG), constituted by [RFC9280], acts as custodian for the RFCXML format. If the RSWG reaches consensus, they can propose a revision to [RFC7991].```

**Comment by elear** [comment]
I can't find the text referred to in this issue.  If it used to be there, perhaps close it?
